FOS\UserBundle\Entity\Group:
    type: mappedSuperclass
    table: Group
    id: {  }
    fields:
        name:
            type: string
            length: 255
            unique: true
        roles:
            type: array
    lifecycleCallbacks: {  }
