fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

assets:
    resource: "@AssetsBundle/Resources/config/routing.yml"
    prefix:   /

bonnezannonces_main:
    resource: "@MainBundle/Resources/config/routing.yml"
    prefix:   /
    
annonce:
    resource: "@MainBundle/Controller/AnnonceController.php"
    type:     annotation

reponse:
    resource: "@MainBundle/Controller/ReponseController.php"
    type:     annotation
